services:
    vortexgin.bca.ewallet.user:
        class: Vortexgin\BCA\eWallet\UserBundle\Manager\UserManager
        arguments:
            - %vortexgin.bca.oauth.host%
            - %vortexgin.bca.oauth.api_id%
            - %vortexgin.bca.oauth.api_secret%
            - %vortexgin.bca.oauth.company_code%
            - '@vortexgin.bca.oauth'
